#pragma once

enum {
    SYS_READ,
    SYS_WRITE,
    SYS_OPEN,
    SYS_CLOSE,
    SYS_IOCTL,
    SYS_YEILD,
    SYS_SPAWN,
    SYS_SHUTDOWN,
    SYS_REBOOT,
    SYS_EXIT,
    SYS_WAITPID,
    SYS_TKILL,
    SYS_MEMINFO,
    SYS_TIME,
    SYS_CHDIR,
    SYS_GETCWD,
    SYS_READDIR,
    SYS_STAT,
    SYS_MMAP,
    SYS_MUNMAP,
    SYS_TASKCOUNT,
    SYS_TASKINFO,
    SYS_MAPFB,
    SYS_SEEK,
    SYS_FEMTOSECONDS
};